### ISSUE TITLE
API Idea

### ISSUE THREAD

**Issue by MadhavBahlMD** [shrutikapoor08/devjoke#391]
Hey @shrutikapoor08 ,
just came across this repo, amazing work 🤩 

How about making a simple API that can return some dev jokes based randomly or based on tags?

Taking that as a part of Hacktoberfest would make it a great project

**Comment by shrutikapoor08** [comment]
Totally! Do you want to create an issue and lead it?

**Comment by MadhavBahlMD** [comment]
Not sure if I can devote enough time to actually implement it, but sure I can open some issues and they can be some good first issues for new contributors during hacktoberfest,

(If time permits, maybe I can also contribute 😋

Closing this issue and opening some new ones
