### ISSUE TITLE
[DevJoke API] Write a script to parse the jokes from README.md to a json file

### ISSUE THREAD

**Issue by MadhavBahlMD** [shrutikapoor08/devjoke#392]
**Idea: DevJoke API**

Todo - Write a script to extract out all the dev jokes from README into a JSON file that can be taken as data for the api

Hint* The jokes in the README are delimited by `* * *`

**Comment by MadhavBahlMD** [comment]
@shrutikapoor08 it should be a very simple task, can you add `good-first-issue` , `first-timers-only` and `hacktoberfest` labels to this issue?

**Comment by iam-agf** [comment]
Can I try this issue?

**Comment by shrutikapoor08** [comment]
@iam-agf Yes!

**Comment by iam-agf** [comment]
Perfect! Is needed an specific language for the parser code or can I use any?

**Comment by shrutikapoor08** [comment]
Anything is okay as long as it gives a json :)

**Comment by iam-agf** [comment]
When you have a bit of free time, please check if the parser is correct or you need something different 🙂

**Comment by MadhavBahlMD** [comment]
@iam-agf please add the parsed JSON result as well,

Let's say in `output` directory, or `parserOutput`

**Comment by hot9cups** [comment]
I've also created a PR trying to resolve this issue, let me know what you think of it
