### ISSUE TITLE
[DevJoke API] Create a server with a route to get all the dev jokes

### ISSUE THREAD

**Issue by MadhavBahlMD** [shrutikapoor08/devjoke#394]
**Project Idea**: DevJoke API 

**Also see**: #392 (Script to parse dev jokes from README.md to JSON file)

**Todo**: Set up a simple server with following routes

1. `/all` - return all the jokes in JSON file
2. `/jokes/:count` - return the top `count` jokes from that json file

Later on we can have a DB associated with this project rather than fetching from JSON, but for start, JSON fetch would do

@shrutikapoor08 does this look good? Do add on if you have any suggestion/modification

**Comment by iam-agf** [comment]
Can I try this one too? Is there a problem if I use JS for this issue instead of Python than in the other one? (I just finished the other one but I will wait for Oct 1st to PR, if there isn't any problem).

**Comment by MadhavBahlMD** [comment]
Sure, @iam-agf you can go ahead with this one as well,

For the tech stack, @shrutikapoor08 will take the final decision

**Comment by shrutikapoor08** [comment]
Wait on this one, since I already have something in the works :)
