### ISSUE TITLE
[DEVJOKES] Think of a good devjoke and add it here.

### ISSUE THREAD

**Issue by shrutikapoor08** [shrutikapoor08/devjoke#395]
Use CONTRIBUTING.MD if this is your first time creating a pull request here. Looking forward to your joke :D

**Comment by shrutikapoor08** [comment]
Why, thank you!

**Comment by Aman-Jamshed** [comment]
Hey @shrutikapoor08  Kindly check my PR #421

**Comment by musavveer** [comment]
Added new jokes #542 
Please do accept my PR.

**Comment by JavaVista** [comment]
Added a new dev joke PR #572 that I think is super funny. Hope you enjoy it. Happy Hacktoberfest! 🎃🎃🎃

**Comment by JLohani** [comment]
Added a joke regarding the Hacktober Fest itself PR #758 . Hope you will like it and successfully accept the PR.

**Comment by shrutikapoor08** [comment]
Thank you for all the jokes everyone! We are slowly but surely getting through all the PRs. Thank you for your patience :)

**Comment by SalmaBliss** [comment]
Hi @shrutikapoor08 ! This is my **first time creating a PR** here ...
Kindly check my PR #514

**Comment by SalmaBliss** [comment]
* #436

**Comment by SalmaBliss** [comment]
Sorry ...
**#592** (New around here)

**Comment by SalmaBliss** [comment]
Added a new joke PR #593. Hope you like it !

**Comment by 547y4m** [comment]
@shrutikapoor08 mam please merge my PR #626 as "hacktoberfest-accepted", it's my 1st time participating in hacktober-fest.
