### ISSUE TITLE
Showing as "Ineligible Repository" for Hacktoberfest 2020

### ISSUE THREAD

**Issue by musavveer** [shrutikapoor08/devjoke#543]

**Comment by shrutikapoor08** [comment]
Can you show screenshot?

**Comment by musavveer** [comment]
Now the PR is showing as pending. 
![Screenshot (34)](https://user-images.githubusercontent.com/62888562/95502189-10354300-09c7-11eb-8e03-02d214aa254f.png)
(?)
Please do approve my PR.
Thanks in advance!!
![Screenshot (32)](https://user-images.githubusercontent.com/62888562/95501957-b7fe4100-09c6-11eb-8800-7f636e57bf19.png)
