### ISSUE TITLE
Hacktoberfest 2021! HECK YEAHHH!! 

### ISSUE THREAD

**Issue by shrutikapoor08** [shrutikapoor08/devjoke#713]
We are ready for your Hacktoberfest 2021! 

Step 1: Think of a DevJoke.
Step 2: Make a PR
Step 3: If your joke gets accepted, we will mark it with `hacktoberfest-accepted` label allowing you to claim it towards Hacktoberfest Tshirt

**Comment by shubhamnag14** [comment]
Please explain to me what i the issue and what is approach to solve it

**Comment by shrutikapoor08** [comment]
> Please explain to me what i the issue and what is approach to solve it

Sure! This is a DevJoke repo. If you know a good devjoke, add it to the repo. Use [contribution guideline](https://github.com/shrutikapoor08/devjoke/blob/master/CONTRIBUTING.MD) to make a PR

**Comment by PronomitaDey** [comment]
Hi @shrutikapoor08 , please check my PR here: https://github.com/shrutikapoor08/devjoke/pull/725

**Comment by sadathshariff** [comment]
Hi @shrutikapoor08, have raised a PR #739 please check it
